### ISSUE TITLE
DRVEGRD 171 MSE Support

### ISSUE THREAD

**Issue by sinanyamaan** [smartmicro/smartmicro_ros2_radars#55]
Hello,

I am trying to create a setup with one **DRVEGRD 171** and two **DRVEGRD 169**s. I have correctly set up the connections via Ethernet and can receive **target pointclouds** from all three sensors.

I am using the umrr9f_t169_msev1.0.0 user interface for the 169s. I chose "mse" because I want to use the detected **objects** from the radars alongside the **targets** in my system.
https://github.com/smartmicro/smartmicro_ros2_radars/blob/ad4e9b211cbfe1d64565ed07559cd841aaadc398/umrr_ros2_driver/src/smartmicro_radar_node.cpp#L280-L288
https://github.com/smartmicro/smartmicro_ros2_radars/blob/ad4e9b211cbfe1d64565ed07559cd841aaadc398/umrr_ros2_driver/src/smartmicro_radar_node.cpp#L303-L322

However, I couldn't find any "mse" interface for the 171. There are three options available for the 171: ummra4_v1.0.0, v1.0.1, and v1.2.1, but they are limited to producing only target output.

- Will there be support for retrieving **ObjectList** from the DRVEGRD 171s soon?
- Or is there a solution for this that I might have missed?
- What does "mse" mean in this context, and why is it required for accessing objects?
- Why can't every radar model produce both targets and objects?

**Comment by smartSRA** [comment]
Hey @sinanyamaan ,

Great to hear that you have successfully set up the driver and sensors. Regarding your questions:

- The MSE feature for DRVEGRD 171 is currently under development, which is why it's not yet available. While I can't provide a specific release date, it's in the pipeline and should be included in an upcoming driver release.

- MSE stands for Mobile Speed Enforcement, a proprietary software module for specific tracking. Only sensors equipped with the MSE software are capable of tracking and outputting objects; others only publish target data.

- MSE is a specialized software application designed for specific radar types, and not all of our sensors are compatible with it due to varying use cases and hardware limitations.

I hope to have answered all your questions, if you require further details or documentations about MSE you may get in contact with our customer support.

**Comment by sinanyamaan** [comment]
Thank you very much for your clear explanations. I am looking forward to the next release!

**Comment by sinanyamaan** [comment]
Thank you very much for your clear explanations. I am looking forward to the next release!
